//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Urzytkownik {
    using System.Runtime.Serialization;
    using System;
    
    
   
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Urzytkownik.DoKonta")]
    public interface DoKonta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Loguj", ReplyAction="http://tempuri.org/DoKonta/LogujResponse")]
        int Loguj(ClientSerwis.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Loguj", ReplyAction="http://tempuri.org/DoKonta/LogujResponse")]
        System.Threading.Tasks.Task<int> LogujAsync(ClientSerwis.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/DoKonta/Odświerz")]
        void Odświerz(ClientSerwis.Urzytkownik ul);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/DoKonta/Odświerz")]
        System.Threading.Tasks.Task OdświerzAsync(ClientSerwis.Urzytkownik ul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Pobierz", ReplyAction="http://tempuri.org/DoKonta/PobierzResponse")]
        ClientSerwis.Urzytkownik Pobierz(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Pobierz", ReplyAction="http://tempuri.org/DoKonta/PobierzResponse")]
        System.Threading.Tasks.Task<ClientSerwis.Urzytkownik> PobierzAsync(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Rejestruj", ReplyAction="http://tempuri.org/DoKonta/RejestrujResponse")]
        int Rejestruj(ClientSerwis.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Rejestruj", ReplyAction="http://tempuri.org/DoKonta/RejestrujResponse")]
        System.Threading.Tasks.Task<int> RejestrujAsync(ClientSerwis.Urzytkownik uk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoKontaChannel : WindowsFormsApp1.Urzytkownik.DoKonta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoKontaClient : System.ServiceModel.ClientBase<WindowsFormsApp1.Urzytkownik.DoKonta>, WindowsFormsApp1.Urzytkownik.DoKonta {
        
        public DoKontaClient() {
        }
        
        public DoKontaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoKontaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoKontaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoKontaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Loguj(ClientSerwis.Urzytkownik uk) {
            return base.Channel.Loguj(uk);
        }
        
        public System.Threading.Tasks.Task<int> LogujAsync(ClientSerwis.Urzytkownik uk) {
            return base.Channel.LogujAsync(uk);
        }
        
        public void Odświerz(ClientSerwis.Urzytkownik ul) {
            base.Channel.Odświerz(ul);
        }
        
        public System.Threading.Tasks.Task OdświerzAsync(ClientSerwis.Urzytkownik ul) {
            return base.Channel.OdświerzAsync(ul);
        }
        
        public ClientSerwis.Urzytkownik Pobierz(int k) {
            return base.Channel.Pobierz(k);
        }
        
        public System.Threading.Tasks.Task<ClientSerwis.Urzytkownik> PobierzAsync(int k) {
            return base.Channel.PobierzAsync(k);
        }
        
        public int Rejestruj(ClientSerwis.Urzytkownik uk) {
            return base.Channel.Rejestruj(uk);
        }
        
        public System.Threading.Tasks.Task<int> RejestrujAsync(ClientSerwis.Urzytkownik uk) {
            return base.Channel.RejestrujAsync(uk);
        }
    }
}
