//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KartyMono.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Urzytkownik", Namespace="http://schemas.datacontract.org/2004/07/GraKarciana")]
    [System.SerializableAttribute()]
    public partial class Urzytkownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Haslo {
            get {
                return this.HasloField;
            }
            set {
                if ((object.ReferenceEquals(this.HasloField, value) != true)) {
                    this.HasloField = value;
                    this.RaisePropertyChanged("Haslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.DoKonta")]
    public interface DoKonta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Loguj", ReplyAction="http://tempuri.org/DoKonta/LogujResponse")]
        int Loguj(KartyMono.ServiceReference1.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Loguj", ReplyAction="http://tempuri.org/DoKonta/LogujResponse")]
        System.Threading.Tasks.Task<int> LogujAsync(KartyMono.ServiceReference1.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/DoKonta/Odświerz")]
        void Odświerz(KartyMono.ServiceReference1.Urzytkownik ul);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/DoKonta/Odświerz")]
        System.Threading.Tasks.Task OdświerzAsync(KartyMono.ServiceReference1.Urzytkownik ul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Pobierz", ReplyAction="http://tempuri.org/DoKonta/PobierzResponse")]
        KartyMono.ServiceReference1.Urzytkownik Pobierz(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Pobierz", ReplyAction="http://tempuri.org/DoKonta/PobierzResponse")]
        System.Threading.Tasks.Task<KartyMono.ServiceReference1.Urzytkownik> PobierzAsync(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Rejestruj", ReplyAction="http://tempuri.org/DoKonta/RejestrujResponse")]
        int Rejestruj(KartyMono.ServiceReference1.Urzytkownik uk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoKonta/Rejestruj", ReplyAction="http://tempuri.org/DoKonta/RejestrujResponse")]
        System.Threading.Tasks.Task<int> RejestrujAsync(KartyMono.ServiceReference1.Urzytkownik uk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoKontaChannel : KartyMono.ServiceReference1.DoKonta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoKontaClient : System.ServiceModel.ClientBase<KartyMono.ServiceReference1.DoKonta>, KartyMono.ServiceReference1.DoKonta {
        
        public DoKontaClient() {
        }
        
        public DoKontaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoKontaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoKontaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoKontaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Loguj(KartyMono.ServiceReference1.Urzytkownik uk) {
            return base.Channel.Loguj(uk);
        }
        
        public System.Threading.Tasks.Task<int> LogujAsync(KartyMono.ServiceReference1.Urzytkownik uk) {
            return base.Channel.LogujAsync(uk);
        }
        
        public void Odświerz(KartyMono.ServiceReference1.Urzytkownik ul) {
            base.Channel.Odświerz(ul);
        }
        
        public System.Threading.Tasks.Task OdświerzAsync(KartyMono.ServiceReference1.Urzytkownik ul) {
            return base.Channel.OdświerzAsync(ul);
        }
        
        public KartyMono.ServiceReference1.Urzytkownik Pobierz(int k) {
            return base.Channel.Pobierz(k);
        }
        
        public System.Threading.Tasks.Task<KartyMono.ServiceReference1.Urzytkownik> PobierzAsync(int k) {
            return base.Channel.PobierzAsync(k);
        }
        
        public int Rejestruj(KartyMono.ServiceReference1.Urzytkownik uk) {
            return base.Channel.Rejestruj(uk);
        }
        
        public System.Threading.Tasks.Task<int> RejestrujAsync(KartyMono.ServiceReference1.Urzytkownik uk) {
            return base.Channel.RejestrujAsync(uk);
        }
    }
}
