//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Tysioc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Urzytkownik", Namespace="http://schemas.datacontract.org/2004/07/GraKarciana")]
    [System.SerializableAttribute()]
    public partial class Urzytkownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HasloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Haslo {
            get {
                return this.HasloField;
            }
            set {
                if ((object.ReferenceEquals(this.HasloField, value) != true)) {
                    this.HasloField = value;
                    this.RaisePropertyChanged("Haslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PodsumowanieTysioc", Namespace="http://schemas.datacontract.org/2004/07/GraKarciana")]
    [System.SerializableAttribute()]
    public partial class PodsumowanieTysioc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] PunktyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] PunktyWTurzeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Punkty {
            get {
                return this.PunktyField;
            }
            set {
                if ((object.ReferenceEquals(this.PunktyField, value) != true)) {
                    this.PunktyField = value;
                    this.RaisePropertyChanged("Punkty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] PunktyWTurze {
            get {
                return this.PunktyWTurzeField;
            }
            set {
                if ((object.ReferenceEquals(this.PunktyWTurzeField, value) != true)) {
                    this.PunktyWTurzeField = value;
                    this.RaisePropertyChanged("PunktyWTurze");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tysioc.ITysioc", CallbackContract=typeof(WindowsFormsApp1.Tysioc.ITysiocCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ITysioc {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/CzekajNaGracza")]
        void CzekajNaGracza(int nr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/CzekajNaGracza")]
        System.Threading.Tasks.Task CzekajNaGraczaAsync(int nr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/Licytuj")]
        void Licytuj(int pk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/Licytuj")]
        System.Threading.Tasks.Task LicytujAsync(int pk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/WyslijKarte")]
        void WyslijKarte(GraKarciana.Karta k, bool Melduj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/WyslijKarte")]
        System.Threading.Tasks.Task WyslijKarteAsync(GraKarciana.Karta k, bool Melduj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/WyslijMusek")]
        void WyslijMusek(GraKarciana.Karta[] k);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/WyslijMusek")]
        System.Threading.Tasks.Task WyslijMusekAsync(GraKarciana.Karta[] k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITysiocCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/ZnalezionoNowychGraczy")]
        void ZnalezionoNowychGraczy(WindowsFormsApp1.Tysioc.Urzytkownik[] gracze);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/TwojaLicytacja")]
        void TwojaLicytacja();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/Twojruch")]
        void Twojruch();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/OdbierzKarty")]
        void OdbierzKarty(GraKarciana.Karta[] karty);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/KtosZalicytowal")]
        void KtosZalicytowal(string Login, int cena);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/KtosWyslalKarte")]
        void KtosWyslalKarte(GraKarciana.Karta k, string s, bool Melduj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/ITysioc/KoniecGry")]
        void KoniecGry(WindowsFormsApp1.Tysioc.PodsumowanieTysioc pk);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITysioc/PodsumowanieRozgrywki")]
        void PodsumowanieRozgrywki(WindowsFormsApp1.Tysioc.PodsumowanieTysioc pk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITysiocChannel : WindowsFormsApp1.Tysioc.ITysioc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TysiocClient : System.ServiceModel.DuplexClientBase<WindowsFormsApp1.Tysioc.ITysioc>, WindowsFormsApp1.Tysioc.ITysioc {
        
        public TysiocClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TysiocClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TysiocClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TysiocClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TysiocClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CzekajNaGracza(int nr) {
            base.Channel.CzekajNaGracza(nr);
        }
        
        public System.Threading.Tasks.Task CzekajNaGraczaAsync(int nr) {
            return base.Channel.CzekajNaGraczaAsync(nr);
        }
        
        public void Licytuj(int pk) {
            base.Channel.Licytuj(pk);
        }
        
        public System.Threading.Tasks.Task LicytujAsync(int pk) {
            return base.Channel.LicytujAsync(pk);
        }
        
        public void WyslijKarte(GraKarciana.Karta k, bool Melduj) {
            base.Channel.WyslijKarte(k, Melduj);
        }
        
        public System.Threading.Tasks.Task WyslijKarteAsync(GraKarciana.Karta k, bool Melduj) {
            return base.Channel.WyslijKarteAsync(k, Melduj);
        }
        
        public void WyslijMusek(GraKarciana.Karta[] k) {
            base.Channel.WyslijMusek(k);
        }
        
        public System.Threading.Tasks.Task WyslijMusekAsync(GraKarciana.Karta[] k) {
            return base.Channel.WyslijMusekAsync(k);
        }
    }
}
